### ISSUE TITLE
How to fix this ??

### ISSUE THREAD

**Issue by Nikolai980** [comicallybad/ComicallyBot2.0#15]
Can you tell me how to fix this error ---> Error connecting Erela

**Comment by comicallybad** [comment]
You're erela must not be set up right. You need to make sure you are on the right version of Java, I have linked it in the readme where to download the correct version of Java. If that doesn't resolve your issue let me know. You have to be running that specific Java version

**Comment by comicallybad** [comment]
As well, make sure you have your application.yml setup correctly, I have updated the readme with new links as the old ones are out of date. Once you setup your password in the yml, make sure you use the same password in the index.js. Lastly, if that doesn't work either, try a different port for your application yml, and index.js. That port could be used already
