### ISSUE TITLE
[Unknown] Question about xp/ mute handler update

### ISSUE THREAD

**Issue by yawn999** [comicallybad/ComicallyBot2.0#21]
where can I configure the XP amount? or change on how much XP you need for level 1, level 2, etc...

Also, I haven't gotten started with the mute handler yet, I'm figuring out how I wanna do it, and it was finals this past week. so I don't have anything to do for a few days.

**Comment by comicallybad** [comment]
When you create an xp role you set what level you wish the role to be acquired at. You can also set an XP multiplier if you wish to make people gain XP faster. `_help addxprole` you can see you set which role you want for a certain level. The xp system isn’t exponential. It does get harder but not exponentially. If you want to change the actual xp algorithm I came up with, you’ll have to replace it in dbFunctions.js. 
`let xpToAdd = Math.floor(Math.random() * 10) + 1;`
`rankupXP = rankupXP = 10 * Math.pow(exists.level + 1, 3) / 5 + 25 - exists.xp;` is the algorithm I came up with.

**Comment by yawn999** [comment]
ok. cause for levels, I was thinking of 
level 0 = 0 xp (ofc. no xp means no level)
level 1 :: 1000 xp
level 2 :: 2000 xp
level 3 :: 3500 xp
level 4 :: 7000 xp
level 5 :: 14000 xp
level 6 :: 25000 xp
level 7 :: 50000 xp
level 8 :: 80000 xp
level 9 :: 125000 xp
level 10 :: 175000 xp

**Comment by comicallybad** [comment]
Yeah if you wanna follow that route you’ll have to make an algorithm. Would seem like you’re doing a mix between *2 and some other math
