### ISSUE TITLE
WHAT IS ERELA PASSWORD?

### ISSUE THREAD

**Issue by GameWax** [comicallybad/ComicallyBot2.0#22]
Yea I have never hosted my own lavalink, I usually use others lavalink nodes, now I clearly don't understand how to get "erela password" and will be grateful if someone explains it all to me....

**Comment by comicallybad** [comment]
Well I’ve tried to explain it as best as I could in the ReadMe.md file and make it as simple as possible. You need to create an application.yml that simply contains the same password as in your .env file. If you add me on discord ComicallyBad#6969 I’d be glad to give you the further help.
