### ISSUE TITLE
latest commit

### ISSUE THREAD

**Issue by IAmDVG** [comicallybad/ComicallyBot2.0#23]
Readding math command.

Going back a few hours ago, you made [This](https://github.com/comicallybad/ComicallyBot2.0/commit/8c2fd89ce2108b643dcf6d8775546d4e354f3e77) commit. Not sure what package you were using before but I found one that might be useful. You can find it [here](https://www.npmjs.com/package/easy-calculation)

**Comment by comicallybad** [comment]
might give it a try, didn't really use the math commands anyways so it wasn't a big deal, but can add it back if the package is useful

**Comment by comicallybad** [comment]
yeah lol that package unfortunately sucks, can solve 2+2, but nothing algebraically. Looking for something that can solve like quadratic roots and linear expressions, maybe even like system of equations and calculus.

**Comment by IAmDVG** [comment]
ok. No worries

**Comment by comicallybad** [comment]
yawn, can you add me on discord? ComicallyBad#6969

**Comment by yawn999** [comment]
sure

**Comment by yawn999** [comment]
I cant. friend requests are off @comicallybad

**Comment by comicallybad** [comment]
> I cant. friend requests are off @comicallybad

ope my bad, try again
