### ISSUE TITLE
any alternative to cleverbot api?

### ISSUE THREAD

**Issue by GameWax** [comicallybad/ComicallyBot2.0#24]
i can't buy the api key, due to some reasons, is there a free alternative for it?

**Comment by comicallybad** [comment]
Yes, however none that are legal. There’s someone I know who has created something similar to clever bot, but it doesn’t have nearly as many responses. I’ll ask him if you can use it

**Comment by GameWax** [comment]
> Yes, however none that are legal. There’s someone I know who has created something similar to clever bot, but it doesn’t have nearly as many responses. I’ll ask him if you can use it

If u have it, then u can send me the api key please

**Comment by comicallybad** [comment]
> If u have it, then u can send me the api key please

he said right now the api is running too slowly for anyone so I don’t have any options for you sorry. Used to be a clever bot free package but it broke. Plus it was piracy anyways. You’d have to unfortunately remove the cleverbot code if you can’t buy a license.
