### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by ImSe4n** [comicallybad/ComicallyBot2.0#26]
Is it possible that you switch to canvacord for the rank card? It will make it look much better.

**Comment by comicallybad** [comment]
I have not heard of canvacard, but looking at it, I like what I see. So I will try to work on implementing this, thanks for the sugggestion!

**Comment by comicallybad** [comment]
I have now made use of canvacord! I made a .env variable so you can replace the background with whatever png file you wish. But it now works and looks pretty cool! Thanks for the suggestion again! (Only wish you could remove the discriminator and then allow for a longer username, but that's the best I could do)
![RankCard](https://user-images.githubusercontent.com/50148901/153323000-fccf2f5a-0a8f-47c1-8bd9-1ad2a88f5b64.png)
