### ISSUE TITLE
HELP WANTED, Looking for Contributors to ComicallyBot

### ISSUE THREAD

**Issue by comicallybad** [comicallybad/ComicallyBot2.0#27]
I have been coding ComicallyBot on my own for over 3+ years, clearly as the repo is named, this is version 2,0. I have updated from v10-v11-v12-v13 all by myself. I am looking to add a ton of features, fix a lot of things and make the bot a lot more readable/understandable to anyone who decides to use it. If you are interested please feel free to reply to this and maybe we can get in touch over discord! I want to add slash commands, but with sooo many commands it will take days most likely with my schedule, since I am a student, I work and do YouTube/Twitch. So if you are interested lmk :) will leave this open for awhile to see if anyone is interested.

**Comment by deepsarda** [comment]
Hello, I am interested.
