### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by programmer-pony** [comicallybad/ComicallyBot2.0#29]
Please consider [choosing a license for your project](https://choosealicense.com/), otherwise we are not allowed to use the code for any purpose all. I would suggest the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.en.html) for a project like this, since it's the only license that states that network use is distribution.

**Comment by programmer-pony** [comment]
What you did is not better because the MIT license requires including a copyright notice, which is not present in this repository.

**Comment by comicallybad** [comment]
I'm not sure why it's much of an issue to you..? It's an open source bot, yeah I don't want people to clone my exact bot and say it's theirs, but that's kinda just what happens when you post something that's open source unfortunately. If you want to use some of the code then go for it. If you want to clone my exact bot to say it's yours then, I see the issue. But this isn't some like professional program I am distributing. I'm not a business, just an individual

**Comment by comicallybad** [comment]
The [MIT License](https://choosealicense.com/licenses/mit/) is short and to the point. It lets people do almost anything they want with your project, like making and distributing closed source versions. I guess that's kinda just what I said. Don't want people stealing my entire bot and claiming it's their own and distributing it, so I guess that's the exact License I should use 😄

**Comment by programmer-pony** [comment]
So you don't want people to "steal" your code so you use a license that allows people to do just that...?

**Comment by comicallybad** [comment]
No the license specially states all distribution must me private.

**Comment by programmer-pony** [comment]
No it doesn't. It literally says users have the right to publish and distribute the software. Have you even read the license?

**Comment by comicallybad** [comment]
Why is this such a big deal to you? If you want to copy everything I’ve done and claim it as your own then no you can’t. Like I said if you want to use some of the code, go for it. I’ve not had a single person complain about a license for a repository before lol.

**Comment by programmer-pony** [comment]
I just want to help because you say you're looking for collaborators while you don't allow people to make copies of the software, but you just don't want to learn. You're missing the whole point of FOSS, you didn't even take the time to read the license, and you're having a disrespectful, negligent, stubborn attitude. You clearly have no interest for FOSS at all. I won't be wasting any more time here. Have a good day.

**Comment by comicallybad** [comment]
How about this, I post a copyright notice saying “All rights reserved” and remove my license. That way, by copyright, no one can distribute my code at all for any profit as I have full copyright 😄
